[package]
name = "polymesh-primitives"
version = "2.0.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
chrono = {version = "0.4.18", default-features = false }

# Ours
polymesh-primitives-derive = { path = "../primitives_derive", default-features = false }

# Other
serde = { version = "1.0.104", optional = true, default-features = false, features = ["derive"] }

# Crypto
confidential_identity = { git = "https://github.com/PolymathNetwork/cryptography.git", branch = "v2-mainnet", default-features = false }
blake2 = { version = "0.9.0", default-features = false }
base64 = { version = "0.12.1", default-features = false, features = ["alloc"] }
rand_core = { version = "0.5", default-features = false }
rand = { version = "0.7.3", default-features = false, optional = true }

# Substrate
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }

sp-core = { package = "sp-core", git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
sp-runtime = { package = "sp-runtime", git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }
sp-runtime-interface = { git = "https://github.com/paritytech/substrate", default-features = false, tag = "v2.0.0" }

[dev-dependencies]
hex = { version = "^0.4.0", default-features = false }
serde_json = "1.0.48"

[features]
default = ["std"]
no_std = [ "confidential_identity/no_std" ]
std = [
	"rand/std",
	"rand_core/std",
	"codec/std",
	"sp-core/std",
	"serde",
	"sp-std/std",
	"sp-version/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"sp-io/std",
	# Crypto
	"confidential_identity/std",
	"confidential_identity/avx2_backend",
	"blake2/std",
	"blake2/simd",
	"polymesh-primitives-derive/std",
	"sp-application-crypto/std",
    "sp-runtime-interface/std",
]

runtime-benchmarks = [
]
