[package]
name = "pallet-transaction-payment"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
# Our deps
polymesh-primitives = { path = "../../primitives", default-features = false  }
polymesh-common-utilities = { path = "../common", default-features = false }

# General 
smallvec = { version = "1.4.0", default-features = false }
serde = { version = "1.0.112", default-features = false }


# Substrate
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
sp-io = { git = "https://github.com/fmiguelgarcia/substrate", default-features = false, branch = "poly-v2.0.0-rc3+1" }
sp-core = { git = "https://github.com/fmiguelgarcia/substrate", default-features = false, branch = "poly-v2.0.0-rc3+1" }
sp-std = { git = "https://github.com/fmiguelgarcia/substrate", default-features = false, branch = "poly-v2.0.0-rc3+1" }
sp-api = { git = "https://github.com/fmiguelgarcia/substrate", default-features = false, branch = "poly-v2.0.0-rc3+1" }
sp-runtime = { git = "https://github.com/fmiguelgarcia/substrate", default-features = false, branch = "poly-v2.0.0-rc3+1" }
frame-support = { git = "https://github.com/fmiguelgarcia/substrate", default-features = false, branch = "poly-v2.0.0-rc3+1" }
frame-system = { git = "https://github.com/fmiguelgarcia/substrate", default-features = false, branch = "poly-v2.0.0-rc3+1" }


[dev-dependencies]
serde_json = "1.0.48"


[features]
default = ["std"]
no_std = []
std = [
	"polymesh-primitives/std",
	"polymesh-common-utilities/std",
	"codec/std",
	"sp-io/std",
	"sp-core/std",
	"sp-api/std",
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
]
