[package]
name = "polymesh"
version = "2.0.0"
authors = ["Anonymous"]
build = "build.rs"
edition = "2018"

[[bin]]
name = "polymesh"
path = "src/main.rs"

[workspace]
members = [
    "bin/bench",
    "bin/crypto-cli",
    "bin/testing",
    "migration-tests",
    "migration-tests/remote-externalities",
    "node-rpc",
    "core/primitives",
    "core/primitives_derive",
    "core/common",
    "core/weights",
    "core/pallets/asset",
    "core/pallets/balances",
    "core/pallets/bridge",
    "core/pallets/committee",
    "core/pallets/compliance-manager",
    "core/pallets/confidential",
    "core/pallets/corporate-actions",
    "core/pallets/group",
    "core/pallets/group/rpc",
    "core/pallets/group/rpc/runtime-api",
    "core/pallets/identity",
    "core/pallets/im-online",
    "core/pallets/multisig",
    "core/pallets/pips",
    "core/pallets/protocol-fee",
    "core/pallets/protocol-fee/rpc",
    "core/pallets/protocol-fee/rpc/runtime-api",
    "core/pallets/settlement",
    "core/pallets/staking",
    "core/pallets/staking/rpc",
    "core/pallets/staking/rpc/runtime-api",
    "core/pallets/statistics",
    "core/pallets/sto",
    "core/pallets/transaction-payment",
    "core/pallets/treasury",
    "core/pallets/utility",
    "core/pallets/contracts",
    "core/runtime/common",
    "core/runtime/extensions",
    "core/runtime/develop",
    "core/runtime/testnet",
    "core/tests",
    "node-rpc",
    "rpc",
    "rpc/runtime-api",
]

[dependencies]
polymesh-primitives = { path = "core/primitives" }
polymesh-common-utilities = { path = "core/common" }

# Our pallets
im-online = { package = "pallet-im-online", path = "core/pallets/im-online" }
pallet-asset = { path = "core/pallets/asset" }
pallet-balances = { path = "core/pallets/balances" }
pallet-committee = { path = "core/pallets/committee" }
pallet-confidential = { path = "core/pallets/confidential" }
pallet-corporate-actions = { path = "core/pallets/corporate-actions" }
pallet-group = { path = "core/pallets/group" }
pallet-protocol-fee = { path = "core/pallets/protocol-fee" }
pallet-staking = { path = "core/pallets/staking" }

polymesh-runtime-common = { path = "core/runtime/common" }

# RPC
node-rpc = { path = "rpc" }
node-rpc-runtime-api = { path = "rpc/runtime-api" }
pallet-contracts-rpc-runtime-api = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
polymesh-node-rpc = { path = "node-rpc" }
frame-system-rpc-runtime-api = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
pallet-protocol-fee-rpc-runtime-api = { path = "core/pallets/protocol-fee/rpc/runtime-api" }
pallet-staking-rpc-runtime-api = { path = "core/pallets/staking/rpc/runtime-api" }
pallet-protocol-fee-rpc = { path = "core/pallets/protocol-fee/rpc" }
pallet-group-rpc = { path = "core/pallets/group/rpc" }
pallet-group-rpc-runtime-api = { path = "core/pallets/group/rpc/runtime-api" }


# Runtimes
polymesh-runtime-develop = { path = "core/runtime/develop" }
polymesh-runtime-testnet = { path = "core/runtime/testnet" }

# General
ed25519-dalek = "1.0.0"
log = "0.4.8"
futures = "0.3.4"
jsonrpc-core = "15.0.0"
serde_json = '1.0.48'
structopt = "0.3.15"
chrono = "0.4.11"

# Substrate
codec = { version = "1.2.0", package = "parity-scale-codec" }
sp-core = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
sp-runtime = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
frame-support = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, tag = "v2.0.1-1" }
sp-api = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
sp-offchain = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
sp-block-builder = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
sp-blockchain = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
sp-session = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
sp-consensus = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
grandpa-primitives = { package = "sp-finality-grandpa", git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
sp-inherents = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
sp-transaction-pool = { package = "sp-transaction-pool", git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
sp-consensus-babe = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
sp-authority-discovery = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }

contracts = { package = "pallet-contracts", git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }

sc-service = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1", features = ["wasmtime"] }
sc-chain-spec = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
sc-client-api = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
sc-executor = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1", features = ["wasmtime"] }
sc-network = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
sc-cli = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1", features = ["wasmtime"] }
sc-telemetry = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
sc-consensus-babe = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
sc-consensus = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
sc-rpc = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
sc-transaction-pool = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
grandpa = { package = "sc-finality-grandpa", git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
sc-basic-authorship = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
sc-authority-discovery = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }

sc-light = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
sc-client-db = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }

prometheus-endpoint = { package = "substrate-prometheus-endpoint", git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }
frame-benchmarking-cli = { git = "https://github.com/PolymathNetwork/substrate", tag = "v2.0.1-1" }

# Other
serde = { version = "1.0.104", default-features = false }

[build-dependencies]
vergen = "3.1.0"

[features]
default = ["std"]
running-ci = [
    "polymesh-runtime-develop/running-ci"
]
default_identity = [
    "polymesh-common-utilities/default_identity"
]
runtime-benchmarks = [
    "polymesh-runtime-develop/runtime-benchmarks",
]
std = [
    "serde/std",
]
