[package]
name = "polymesh"
version = "2.0.0"
authors = ["Anonymous"]
build = "build.rs"
edition = "2018"

[[bin]]
name = "polymesh"
path = "src/main.rs"

[workspace]
members = [
    "primitives",
    "primitives_derive",
    "pallets/runtime/common",
    "pallets/runtime/develop",
    "pallets/runtime/testnet-v1",
    "pallets/common",
    "pallets/transaction-payment",
    "pallets/staking",
    "pallets/staking/rpc",
    "pallets/staking/rpc/runtime-api",
    "pallets/staking/reward-curve",
    "pallets/pips",
    "pallets/identity",
    "pallets/im-online",
    "pallets/balances",
    "pallets/committee",
    "pallets/group",
    "pallets/group/rpc",
    "pallets/group/rpc/runtime-api",
    "pallets/protocol-fee",
    "pallets/multisig",
    "pallets/cdd-offchain-worker",
    "pallets/protocol-fee/rpc",
    "pallets/protocol-fee/rpc/runtime-api",
    "pallets/treasury",
    "pallets/cdd-offchain-worker",
    "pallets/asset",
    "pallets/compliance-manager",
    "pallets/statistics",
    "pallets/compliance-manager/rpc",
    "pallets/compliance-manager/rpc/runtime-api",
    "pallets/confidential",
    "pallets/utility",
    "rpc/runtime-api",
    "node-rpc",
    "rpc",
    "utils/wasm-builder",
]

[dependencies]
# Common
# polymesh-primitives = { path = "primitives", default-features = false }
# polymesh-common-utilities = { path = "pallets/common", default-features = false }
# polymesh-runtime-common = { path = "pallets/runtime/common", default-features = false }

# Runtimes
polymesh-runtime-develop = { path = "pallets/runtime/develop", default-features = false }
polymesh-runtime-testnet-v1 = { path = "pallets/runtime/testnet-v1" }

# Out pallets
# pallet-asset = { path = "pallets/asset", default-features = false }
# pallet-treasury = { path = "pallets/treasury", default-features = false }
# pallet-confidential = { path = "pallets/confidential", default-features = false }
# pallet-protocol-fee = { path = "pallets/protocol-fee", default-features = false }
# im-online = { package = "pallet-im-online", path = "pallets/im-online", default-features = false }

# RPC
# node-rpc = { path = "rpc", default-features = false }
# node-rpc-runtime-api = { path = "rpc/runtime-api", default-features = false }
# pallet-protocol-fee-rpc-runtime-api = { path = "pallets/protocol-fee/rpc/runtime-api", default-features = false }
# pallet-contracts-rpc-runtime-api = { path = "pallets/contracts/rpc/runtime-api", default-features = false}
# pallet-staking-rpc-runtime-api = { path = "pallets/staking/rpc/runtime-api", default-features = false }
# pallet-protocol-fee-rpc = { path = "pallets/protocol-fee/rpc", default-features = false }
# pallet-group-rpc = { path = "pallets/group/rpc", default-features = false }
# pallet-group-rpc-runtime-api = { path = "pallets/group/rpc/runtime-api", default-features = false }
# pallet-compliance-manager-rpc = { path = "pallets/compliance-manager/rpc", default-features = false }
# pallet-compliance-manager-rpc-runtime-api = { path = "pallets/compliance-manager/rpc/runtime-api", default-features = false }
# polymesh-node-rpc = { package = "polymesh-node-rpc", path = "node-rpc"}

# Others
# parking_lot = "0.10.0"
# tokio = "0.2.13"
# ctrlc = { version = "3.1.4", features = ["termination"] }
# lazy_static = "1.4.0"
# log = "0.4.8"
# futures = "0.3.4"
# hex-literal = "0.2.1"
# jsonrpc-core = "14.0.5"
# serde_json = '1.0.48'
# structopt = "0.3.15"
# chrono = { version = "0.4.11", default-features = false }
# linregress = { version = "0.1", optional = true }
# rand = { version = "0.7.3" } 
# rand_core = { version = "0.5" }

# Substrate
# codec = { version = "1.2.0", package = "parity-scale-codec" }
# frame-benchmarking = { package = "frame-benchmarking", git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sc-rpc = { git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sc-chain-spec = { git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sp-api = { git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sp-io = { git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sp-offchain = { git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sp-block-builder = { git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sp-blockchain = { git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sp-runtime = { git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sp-session = { git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sp-core = { package = "sp-core", git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sc-client-api = { git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sc-client-db = { package = "sc-client-db", git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sc-executor = { git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sc-network = { package = "sc-network", git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sp-consensus = { package = "sp-consensus", git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# grandpa = { package = "sc-finality-grandpa", git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# grandpa-primitives = { package = "sp-finality-grandpa", git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sp-inherents = { package = "sp-inherents", git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sc-service = { git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sc-cli = { git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sc-telemetry = { package = "sc-telemetry", git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sc-transaction-pool = { package = "sc-transaction-pool", git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sp-transaction-pool = { package = "sp-transaction-pool", git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sc-keystore = { git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sc-consensus-babe = { package = "sc-consensus-babe", git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sp-consensus-babe = { package = "sp-consensus-babe", git = "https://github.com/fmiguelgarcia/substrate", default-features = false, branch = "poly-v2.0.0-rc3+1" }
# sc-consensus = {git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sc-basic-authorship = { package = "sc-basic-authorship", git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# contracts = { package = "pallet-contracts", path = "pallets/contracts" }
# sc-authority-discovery = { package = "sc-authority-discovery", git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# sp-authority-discovery = { package = "sp-authority-discovery", git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# contracts-rpc = { package = "pallet-contracts-rpc", path = "pallets/contracts/rpc" }
# prometheus-endpoint = { package = "substrate-prometheus-endpoint", git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# frame-system-rpc-runtime-api = { package = "frame-system-rpc-runtime-api", git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
# frame-benchmarking-cli = { git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }

[build-dependencies]
# vergen = "3.1.0"

#[patch."https://github.com/fmiguelgarcia/substrate"]
#sp-core = { git = "https://github.com/fmiguelgarcia/substrate", default-features = false, branch = "poly-v2.0.0-rc3+1" }
[patch.crates-io]
substrate-bip39 = { git = 'https://github.com/fmiguelgarcia/substrate-bip39', branch = 'poly-v2.0.0-rc3+1', default-features = false}

#[profile.dev.package.curve25519-dalek]
#version = "2"
#default_features = false
#features = ["nigthly"]
#opt-level = 3

#[profile.dev.package.ed25519-dalek]
#opt-level = 3
#default_features = false
#features = ["nigthly"]

#[profile.dev.package.x25519-dalek]
#opt-level = 3 
#default_features = false


[features]
default = []
default_identity = [
#    "polymesh-common-utilities/default_identity"
]
runtime-benchmarks = [
#    "linregress",
#    "polymesh-runtime-common/runtime-benchmarks",
]
