[package]
name = "node-rpc"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
node-rpc-runtime-api = { path = "./runtime-api" }

polymesh-primitives = { path = "../primitives", default-features = false }
pallet-pips = { path = "../pallets/pips", default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0" }
sp-rpc = { git = 'https://github.com/fmiguelgarcia/substrate', default_features = false, branch = "poly-v2.0.0-rc3+1"}
sp-runtime = { git = "https://github.com/fmiguelgarcia/substrate", default-features = false, branch = "poly-v2.0.0-rc3+1" }
sp-blockchain = { git = 'https://github.com/fmiguelgarcia/substrate', default_features = false, branch = "poly-v2.0.0-rc3+1"}
sp-std = {git = 'https://github.com/fmiguelgarcia/substrate', default_features = false, branch = "poly-v2.0.0-rc3+1" }
sp-api = {git = 'https://github.com/fmiguelgarcia/substrate', default_features = false, branch = "poly-v2.0.0-rc3+1" }
frame-support = { git = "https://github.com/fmiguelgarcia/substrate", default-features = false, branch = "poly-v2.0.0-rc3+1"}

# Others
serde = { version = "1.0.104", features = ["derive"] }
jsonrpc-core = "14.0.5"
jsonrpc-core-client = "14.0.5"
jsonrpc-derive = "14.0.5"

[features]
default = ["std"]
std = [
	"polymesh-primitives/std",
	"pallet-pips/std",
	"frame-support/std",
	"sp-runtime/std",
]
