[package]
name = "pallet-utility"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", optional = true }

codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, version = "2.0.0-rc3" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, version = "2.0.0-rc3" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, version = "2.0.0-rc3" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, version = "2.0.0-rc3" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, version = "2.0.0-rc3" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, version = "2.0.0-rc3" }

[dev-dependencies]
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, version = "2.0.0-rc3" }
# pallet-balances = { version = "2.0.0-alpha.2", path = "../balances" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"sp-io/std",
	"sp-std/std"
]
