[package]
name = "pallet-staking-rpc-runtime-api"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
sp-api = { git = "https://github.com/PolymathNetwork/substrate", default_features = false, branch = "remove-subtype-trait"}
sp-runtime = { git = "https://github.com/PolymathNetwork/substrate", default_features = false,  branch = "remove-subtype-trait"}
frame-support = { git = "https://github.com/PolymathNetwork/substrate", default-features = false, branch = "remove-subtype-trait" }

[dev-dependencies]
serde_json = "1.0.48"

[features]
default = ["std"]
std = [
	"sp-api/std",
	"sp-runtime/std",
	"frame-support/std"
]