jobs:
- name: test
  plan:
  - task: run-unit
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: ls
        args: ["-a"]
