resources:
- name: Polymesh
  type: git
  icon: github
  source:
    uri: git@github.com:cwsatpolymath/Polymesh.git
    branch: ((helloworld_branch))
    private_key: ((polymesh-github.id_concourse_rsa))

jobs:
- name: test
  plan:
  - get: Polymesh
    trigger: false
  - task: run-unit
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: ls
        args: ["-a"]
