---

resources:
  - name: git-polymesh
    type: git
    icon: github
    check_every: 5m
    source:
      uri: git@github.com:cwsatpolymath/Polymesh.git
      branch: concourse-test
      private_key: ((polymesh-github.id_concourse_rsa))
  - name: s3-polymesh
    type: s3
    source:
      bucket: polymesh-testnet-artifacts
      region_name: ca-central-1
      regexp: concourse/polymesh/release-(.*)
      access_key_id: ((s3-polymath-concourse.access_key_id))
      secret_access_key: ((s3-polymath-concourse.secret_access_key))

jobs:
  - name: build-polymesh
    plan:
      - get: git-polymesh
        trigger: true
        version: every
      - in_parallel:
        - task: run-lint
          config:
            inputs:
              - name: git-polymesh
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: polymathnetwork/rust
                aws_access_key_id: ((polymath-ecr.aws-access-id))
                aws_secret_access_key: ((polymath-ecr.aws-access-secret))
                aws_region: us-east-1
            run:
              dir: git-polymesh
              path: bash
              args: [".concourse/scripts/t-rustfmt-lint.sh"]
        - task: cargo-build
          config:
            inputs:
              - name: git-polymesh
            caches:
              - path: git-polymesh/target
              - path: /usr/local/cargo
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: polymathnetwork/rust
                aws_access_key_id: ((polymath-ecr.aws-access-id))
                aws_secret_access_key: ((polymath-ecr.aws-access-secret))
                aws_region: us-east-1
            run:
              path: bash
              args: ["git-polymesh/.concourse/scripts/t-cargo-build.sh", "git-polymesh", "build-caches"]
            outputs:
              - name: build-caches
      - in_parallel:
        - task: cargo-test
          config:
            inputs:
              - name: git-polymesh
              - name: build-caches
            caches:
              - path: git-polymesh/target
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: polymathnetwork/rust
                aws_access_key_id: ((polymath-ecr.aws-access-id))
                aws_secret_access_key: ((polymath-ecr.aws-access-secret))
                aws_region: us-east-1
            run:
              path: bash
              args: ["git-polymesh/.concourse/scripts/t-cargo-test.sh", "git-polymesh", "build-caches"]
      - put: s3-polymesh
        params:
          file: artifact/polymesh-*
          acl: public-read
#        - task: cargo-clippy
#          config:
#            inputs:
#              - name: git-polymesh
#              - name: build-caches
#            platform: linux
#            image_resource:
#              type: registry-image
#              source:
#                repository: polymathnetwork/rust
#                aws_access_key_id: ((polymath-ecr.aws-access-id))
#                aws_secret_access_key: ((polymath-ecr.aws-access-secret))
#                aws_region: us-east-1
#            run:
#              path: bash
#              args: ["git-polymesh/.concourse/scripts/t-lint-clippy.sh", "git-polymesh", "build-caches"]
#          on_failure:
#            task: ignore_clippy
#            config:
#              platform: linux
#              image_resource:
#                type: registry-image
#                source: { repository: busybox }
#              run:
#                path: echo
#                args:
#                  - "Ignoring clippy failure"
#
