---

resources:
  - name: r-git-polymesh
    type: git
    icon: github
    check_every: 5m
    source:
      uri: git@github.com:cwsatpolymath/Polymesh.git
      branch: concourse-test
      private_key: ((polymesh-github.id_concourse_rsa))

jobs:
  - name: j-build-polymesh
    plan:
      - get: r-git-polymesh
        trigger: true
        version: every
      - in_parallel:
        - task: t-run-lint
          config:
            inputs:
              - name: r-git-polymesh
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: polymathnetwork/rust
                aws_access_key_id: ((polymath-ecr.aws-access-id))
                aws_secret_access_key: ((polymath-ecr.aws-access-secret))
                aws_region: us-east-1
            run:
              dir: r-git-polymesh
              path: bash
              args: [".concourse/scripts/t-rustfmt-lint.sh"]
        - task: t-cargo-build
          config:
            inputs:
              - name: r-git-polymesh
            platform: linux
            caches:
              - path: r-git-polymesh/target
              - path: /usr/local/cargo
            image_resource:
              type: registry-image
              source:
                repository: polymathnetwork/rust
                aws_access_key_id: ((polymath-ecr.aws-access-id))
                aws_secret_access_key: ((polymath-ecr.aws-access-secret))
                aws_region: us-east-1
            run:
              path: bash
              args: ["r-git-polymesh/.concourse/scripts/t-cargo-build.sh", "r-git-polymesh", "build-caches"]
            outputs:
              - name: build-caches
      - in_parallel:
        - task: t-cargo-test
          config:
            inputs:
              - name: r-git-polymesh
              - name: build-caches
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: polymathnetwork/rust
                aws_access_key_id: ((polymath-ecr.aws-access-id))
                aws_secret_access_key: ((polymath-ecr.aws-access-secret))
                aws_region: us-east-1
            run:
              path: bash
              args: ["r-git-polymesh/.concourse/scripts/t-cargo-test.sh", "r-git-polymesh", "build-caches"]
#        - task: t-cargo-clippy
#          config:
#            inputs:
#              - name: r-git-polymesh
#              - name: build-caches
#            platform: linux
#            image_resource:
#              type: registry-image
#              source:
#                repository: polymathnetwork/rust
#                aws_access_key_id: ((polymath-ecr.aws-access-id))
#                aws_secret_access_key: ((polymath-ecr.aws-access-secret))
#                aws_region: us-east-1
#            run:
#              path: bash
#              args: ["r-git-polymesh/.concourse/scripts/t-lint-clippy.sh", "r-git-polymesh", "build-caches"]
#          on_failure:
#            task: ignore_clippy
#            config:
#              platform: linux
#              image_resource:
#                type: registry-image
#                source: { repository: busybox }
#              run:
#                path: echo
#                args:
#                  - "Ignoring clippy failure"
#
