[package]
name = "pallet-confidential"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
polymesh-primitives = { path = "../../primitives", default-features = false }
polymesh-primitives-derive = { path = "../../primitives_derive", default-features = false }
polymesh-common-utilities = { path = "../common", default-features = false }

pallet-identity = { path = "../identity", default-features = false }

# Other
serde = { version = "1.0.104", default-features = false }
serde_derive = { version = "1.0.104", optional = true, default-features = false}

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }

frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }

pallet-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-session = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }

sp-runtime-interface = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }

# Crypto
rand_core = { version = "0.5", default-features = false }
rand = { version = "0.7.3", default-features = false, optional = true } 
cryptography = { path = "../../external/cryptography", default-features = false }
curve25519-dalek = { version = "2", default-features = false, features = ["nightly"] }
bulletproofs = { git = "https://github.com/fmiguelgarcia/bulletproofs.git", tag = "2.0.0-polymath-1", default-features = false }

[dev-dependencies]
test-client = { package = "substrate-test-runtime-client", git = "https://github.com/paritytech/substrate", rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
lazy_static = "1.4.0"

[features]
equalize = []
only-staking = []
default = ["std", "equalize", "avx2_backend"]

# Backends
u32_backend = [ "cryptography/u32_backend"]
u64_backend = [ "cryptography/u64_backend"]
avx2_backend = [ "cryptography/avx2_backend"]

no_std = [
	"cryptography/no_std"
]

std = [
	"serde_derive",
	"rand/std",
	"cryptography/std",
	"rand_core/std",
	"codec/std",
	"serde/std",
	"sp-core/std",
	"sp-std/std",
	"sp-io/std",
	"sp-api/std",
	"sp-arithmetic/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"polymesh-primitives/std",
	"pallet-session/std",
	"sp-runtime-interface/std",
]
