[package]
name = "polymesh-primitives-derive"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.8", features = ["visit-mut"] }
quote = "1.0.2"
proc-macro2 = "1.0.6"

[features]
default = ["std"]
no_std = []
std = []
