[package]
name = "permissions"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.12"
regex = "1"
lazy_static = "1"
serde =  { version = "1", features = ["derive"] }
serde_json ="1"