[package]
name = "pallet-mips-rpc-runtime-api"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
sp-api = { rev = '93569d0d1af7aa5eb67b9de8b58d7fffde63b421', git = 'https://github.com/paritytech/substrate.git', default_features = false}
sp-std = { rev = '93569d0d1af7aa5eb67b9de8b58d7fffde63b421', git = 'https://github.com/paritytech/substrate.git', default_features = false }
sp-runtime = { rev = '93569d0d1af7aa5eb67b9de8b58d7fffde63b421', git = 'https://github.com/paritytech/substrate.git', default_features = false }
frame-support = { git = "https://github.com/paritytech/substrate", rev = "93569d0d1af7aa5eb67b9de8b58d7fffde63b421", default-features = false }

[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ["std"]
std = [
    "serde",
	"sp-api/std",
	"codec/std",
	"sp-std/std",
	"sp-runtime/std",
]