[package]
name = "pallet-transaction-payment-rpc"
version = "2.0.0-rc3"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
jsonrpc-core = "14.2.0"
jsonrpc-core-client = "14.2.0"
jsonrpc-derive = "14.2.1"

# Substrate
codec = { package = "parity-scale-codec", version = "1.3.0" }
sp-core = { git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
sp-rpc = { git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
sp-runtime = { package = "sp-runtime", git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
sp-blockchain = { git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
sp-api = { git = "https://github.com/fmiguelgarcia/substrate", branch = "poly-v2.0.0-rc3+1" }
