[package]
name = "pallet-transaction-payment-rpc"
version = "2.0.0-rc3"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0" }
jsonrpc-core = "14.2.0"
jsonrpc-core-client = "14.2.0"
jsonrpc-derive = "14.2.1"
sp-core = { package = "sp-core", git = "https://github.com/paritytech/substrate", version = "2.0.0-rc3" }
sp-rpc = { package = "sp-rpc", git = "https://github.com/paritytech/substrate", version = "2.0.0-rc3" }
serde = { version = "1.0.104", features = ["derive"] }
sp-runtime = { package = "sp-runtime", git = "https://github.com/paritytech/substrate", version = "2.0.0-rc3" }
sp-blockchain = { package = "sp-blockchain", git = "https://github.com/paritytech/substrate", version = "2.0.0-rc3" }
pallet-transaction-payment-rpc-runtime-api = { version = "2.0.0-rc3", path = "./runtime-api" }
sp-api = { package = "sp-api", git = "https://github.com/paritytech/substrate", version = "2.0.0-rc3" }
