[package]
name = "polymesh-runtime-develop-wasm"
version = "0.1.0"
authors = ["Polymath Inc."]
edition = "2018"

[profile.release]
lto = true
panic = 'abort'

[profile.dev]
panic = 'abort'

[lib]
crate-type = ['cdylib']

[dependencies]
polymesh-runtime-develop = { path = "..", default-features = false }

[features]
default = []
no_std = [
	"polymesh-runtime-develop/no_std"
]
std = ["polymesh-runtime-develop/std"]

[workspace]
members = []
