[package]
name = "pallet-identity-rpc"
version = "0.1.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
polymesh-primitives = { path = "../../../primitives", default-features = false }

# General
serde = { version = "1.0.104", features = ["derive"] }
jsonrpc-core = "14.0.5"
jsonrpc-core-client = "14.0.5"
jsonrpc-derive = "14.0.5"

# Substrate
codec = { package = "parity-scale-codec", version = "1.1.2" }
sp-core = { git = 'https://github.com/fmiguelgarcia/substrate', default-features = false, branch = "poly-v2.0.0-rc3+1" }
sp-rpc = { git = 'https://github.com/fmiguelgarcia/substrate', default-features = false, branch = "poly-v2.0.0-rc3+1" }
sp-runtime = { git = 'https://github.com/fmiguelgarcia/substrate', default-features = false, branch = "poly-v2.0.0-rc3+1" }
sp-blockchain = { git = 'https://github.com/fmiguelgarcia/substrate', default-features = false, branch = "poly-v2.0.0-rc3+1" }
sp-api = { git = 'https://github.com/fmiguelgarcia/substrate', default-features = false, branch = "poly-v2.0.0-rc3+1" }
