---

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
  - name: githubpr-polymesh
    type: pull-request
    webhook_token: ((cwsatpolymath-polymesh-webhook-token))
    source:
      repository: cwsatpolymath/Polymesh
      access_token: ((github-pat-claus))
  - name: s3-polymesh
    type: s3
    source:
      bucket: polymesh-testnet-artifacts
      region_name: ca-central-1
      regexp: concourse/polymesh/polymesh-(.*)
      access_key_id: ((s3-polymath-concourse.access_key_id))
      secret_access_key: ((s3-polymath-concourse.secret_access_key))
  - name: dockerimage-polymesh
    type: docker-image
    source:
      repository: 414255671868.dkr.ecr.us-east-1.amazonaws.com/polymathnetwork/polymesh
      aws_access_key_id: ((polymath-ecr.aws-access-id))
      aws_secret_access_key: ((polymath-ecr.aws-access-secret))
  - name: semver-git-polymesh
    type: semver
    source:
      driver: git
      uri: git@github.com:polymathnetwork/concourse-semver-tracking
      branch: master
      file: polymesh/version
      private_key: ((github-polymathnetwork-concourse-semver-tracking.id_rsa))
  - name: semver-git-polymesh-cli
    type: semver
    source:
      driver: git
      uri: git@github.com:polymathnetwork/concourse-semver-tracking
      branch: master
      file: polymesh-cli/version
      private_key: ((github-polymathnetwork-concourse-semver-tracking.id_rsa))

jobs:
  - name: build-polymesh
    plan:
      - get: githubpr-polymesh
        trigger: true
        version: every
      - get: semver-git-polymesh
        params:
          bump: patch
          pre: rc
      - get: semver-git-polymesh-cli
        params:
          bump: patch
          pre: rc
      - in_parallel:
        - task: run-lint
          config:
            inputs:
              - name: githubpr-polymesh
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: polymathnetwork/rust
                tag: debian-1.44.1
                aws_access_key_id: ((polymath-ecr.aws-access-id))
                aws_secret_access_key: ((polymath-ecr.aws-access-secret))
                aws_region: us-east-1
            run:
              dir: githubpr-polymesh
              path: bash
              args: [".concourse/scripts/t-rustfmt-lint.sh"]
        - task: cargo-build
          config:
            inputs:
              - name: githubpr-polymesh
              - name: semver-git-polymesh
            caches:
              - path: githubpr-polymesh/target
              - path: /usr/local/cargo
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: polymathnetwork/rust
                tag: debian-1.44.1
                aws_access_key_id: ((polymath-ecr.aws-access-id))
                aws_secret_access_key: ((polymath-ecr.aws-access-secret))
                aws_region: us-east-1
            run:
              path: bash
              args: ["githubpr-polymesh/.concourse/scripts/t-cargo-build.sh", "githubpr-polymesh", "build-caches"]
            outputs:
              - name: build-caches
              - name: artifact
              - name: dockerdir
        - task: npm-install
          config:
            inputs:
              - name: githubpr-polymesh
              - name: semver-git-polymesh-cli
            caches:
              - path: githubpr-polymesh/scripts/cli/node_modules
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: polymathnetwork/node
                tag: 14
                aws_access_key_id: ((polymath-ecr.aws-access-id))
                aws_secret_access_key: ((polymath-ecr.aws-access-secret))
                aws_region: us-east-1
            run:
              path: bash
              args: ["githubpr-polymesh/.concourse/scripts/t-npm-install.sh", "githubpr-polymesh", "npm-caches"]
            outputs:
              - name: npm-caches
      - in_parallel:
        - task: cargo-test
          config:
            inputs:
              - name: githubpr-polymesh
              - name: build-caches
            caches:
              - path: githubpr-polymesh/target
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: polymathnetwork/rust
                tag: debian-1.44.1
                aws_access_key_id: ((polymath-ecr.aws-access-id))
                aws_secret_access_key: ((polymath-ecr.aws-access-secret))
                aws_region: us-east-1
            run:
              path: bash
              args: ["githubpr-polymesh/.concourse/scripts/t-cargo-test.sh", "githubpr-polymesh", "build-caches"]
        - task: npm-test
          config:
            inputs:
              - name: githubpr-polymesh
              - name: artifact
              - name: npm-caches
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: polymathnetwork/node
                tag: 14
                aws_access_key_id: ((polymath-ecr.aws-access-id))
                aws_secret_access_key: ((polymath-ecr.aws-access-secret))
                aws_region: us-east-1
            run:
              path: bash
              args: ["githubpr-polymesh/.concourse/scripts/t-npm-test.sh", "githubpr-polymesh", "npm-caches", "artifact"]
      - put: s3-polymesh
        params:
          file: artifact/polymesh-*
          acl: public-read
      - put: dockerimage-polymesh
        params:
          build: dockerdir
          tag_file: dockerdir/tag_file
          additional_tags: dockerdir/additional_tags

